name: MAUI CI/CD
on:
    push:
        branches: ["workflow-building"]
    pull_request:
        branches: ["workflow-building"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

env:
    APP_NAME: com.companyname.FrienDex
    RELEASE_PATH: .\FrienDex\bin\Release\net10.0-android\
    APP_SUFFIX: -Signed.apk

jobs:
    build-android:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.0.x'

            # - name: Run a one-line script
            #   run: gh release upload --help



            - name: Install MAUI workload
              run: dotnet workload install maui

            - name: Build
              run:
                  dotnet publish
                  -f net10.0-android
                  -c Release
                  -p:AndroidPackageFormat=apk

            - name: List build output
              run: ls -R ./**/*-Signed.apk


            - name: Run a one-line script
              run: echo Hello, world!

            # - name: Upload binaries to release
            #   uses: svenstaro/upload-release-action@v2
            #   with:
            #     repo_token: ${{ secrets.GITHUB_TOKEN }}
            #     file: ./**/*-Signed.apk
            #     tag: ${{ github.ref }}-test
            #     target_commit: ${{ github.ref }}
            #     overwrite: true
            #     body: "This is my release text"

            - name: 'package release'
              run: |
                dir
                gh release list
                gh release create ${{ github.ref_name }}-release-v${{ github.run_number }}
                gh release upload ${{ github.ref_name }}-release-v${{ github.run_number }} ${{ env.RELEASE_PATH }}${{ env.APP_NAME }}${{ env.APP_SUFFIX }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash


